/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActionStep { 'description' : string }
export interface Medication {
  'dosage' : string,
  'name' : string,
  'purpose' : string,
}
export type ReportId = bigint;
export interface SimplifiedSummary {
  'actionSteps' : Array<ActionStep>,
  'medications' : Array<Medication>,
  'keyFindings' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteReport' : ActorMethod<[ReportId], undefined>,
  'getHistory' : ActorMethod<[], Array<[Time, string, ReportId, boolean]>>,
  'getSummary' : ActorMethod<[ReportId], SimplifiedSummary>,
  'submitReport' : ActorMethod<
    [string, string, Array<string>, Array<Medication>, Array<ActionStep>],
    ReportId
  >,
  'toggleBookmark' : ActorMethod<[ReportId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];