/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ReportId = IDL.Nat;
export const ActionStep = IDL.Record({ 'description' : IDL.Text });
export const Medication = IDL.Record({
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'purpose' : IDL.Text,
});
export const SimplifiedSummary = IDL.Record({
  'actionSteps' : IDL.Vec(ActionStep),
  'medications' : IDL.Vec(Medication),
  'keyFindings' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, IDL.Text, ReportId))],
      ['query'],
    ),
  'getSummary' : IDL.Func([ReportId], [SimplifiedSummary], ['query']),
  'submitReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(Medication),
        IDL.Vec(ActionStep),
      ],
      [ReportId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ReportId = IDL.Nat;
  const ActionStep = IDL.Record({ 'description' : IDL.Text });
  const Medication = IDL.Record({
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const SimplifiedSummary = IDL.Record({
    'actionSteps' : IDL.Vec(ActionStep),
    'medications' : IDL.Vec(Medication),
    'keyFindings' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, IDL.Text, ReportId))],
        ['query'],
      ),
    'getSummary' : IDL.Func([ReportId], [SimplifiedSummary], ['query']),
    'submitReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(Medication),
          IDL.Vec(ActionStep),
        ],
        [ReportId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };